# Generated by Django 6.0.6 on 2026-06-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_name_category_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accent',
            field=models.CharField(default='#d4af37', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='#1a1a2e', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pattern',
            field=models.CharField(default='solid', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
